Don't set initial value of there is Element has property value
vaadin/vaadin-date-picker-flow pull request #275
Opened 2020-09-20 18:39 UTC by denis-anisimov

Fixes #274

2020-09-25 13:25 UTC, mshabarov requested changes

2020-09-25 13:25 UTC, mshabarov commented on vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> +        super(initialDate, null, String.class, PARSER, FORMATTER, false);
Call `this(initialDate, false)` instead

2020-09-25 13:25 UTC, mshabarov commented on vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePicker.java
> +            boolean isInitialValueOptional) {
Add `isInitialValueOptional` to javadoc

2020-09-28 06:38 UTC, denis-anisimov commented on vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
> +        super(initialDate, null, String.class, PARSER, FORMATTER, false);
Leftover, thanks.

2020-09-28 07:24 UTC, mshabarov approved these changes

2020-09-28 07:25 UTC, merged